### ISSUE TITLE
How to use this.router.resetConfig()?

### ISSUE THREAD

**Issue by pilomat** [penleychan/ngx-transloco-router#11]
How to init array of routes dynamically?

I tried to follow this [conversation](https://github.com/gilsdav/ngx-translate-router/issues/99) but the implementation are different.

**Comment by penleychan** [comment]
Can you provide an example project?
Basically from what I can derived from that issue over ngx-translate-router is that you need to implement your own parser that load the routes. You can do that as there is an option to provide your own parser:
https://github.com/penleychan/ngx-transloco-router/blob/master/libs/ngx-transloco-router/src/lib/localize-router.module.ts#L125

So it would pretty much be the same:
```
LocalizeRouterModule.forRoot(routes, {
  parser: {
    ...your implementation
  }
}),
```
I'm not even sure if the original poster of that conversation got it working as it was closed by the owner of the library.

**Comment by pilomat** [comment]
I solved this issue with the follow implementation:

`

    constructor(
      translateService: TranslocoService,
      location1: Location,
      injector: Injector,
      private mobileRouters: Routes,
      private deviceDetectorService: DeviceDetectorService) {   super(translateService, location1, injector.get(LOCALIZE_ROUTER_CONFIG) as LocalizeRouterConfig);}
`
`
  load(routes: Routes): Promise<any> {
    return new Promise((resolve: any) => {
      this.deviceDetectorService.isMobile() ? this.init(this.mobileRouters).then(resolve) : this.init(routes).then(resolve)
    })}
}

`

`
LocalizeRouterModule.forRoot(routes, {parser: {
        provide: LocalizeParser,
        useFactory: (translate: TranslocoService, location: Location, injector: Injector, routers: Routes, detector: DeviceDetectorService) => new RouterLocalizeParser(translate, location, injector, routers, detector),
        deps: [TranslocoService, Location, Injector, MOBILE_ROUTERS, DeviceDetectorService]
      }}),`
      
     
this implementation works only with Angular 15 and with version 15.0.0 after introducing the parser as a parameter to the forRoot method. 

I could not get it to work in the previous version of Angular, where the parser was still in the provider declaration. 

I really appreciate your proactivity and quick response in this project. Thank you :-)

**Comment by pilomat** [comment]
I just realized that the routing is not being handled properly. The console throws this error:
`
app.component.html:12 ERROR TypeError: Cannot read properties of undefined (reading 'indexOf')
    at RouterLocalizeParser.getLocationLang (penleychan-ngx-transloco-router.mjs:279:51)
    at Object.next (penleychan-ngx-transloco-router.mjs:801:46)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at pairwise.js:10:35
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at filter.js:6:128
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)

`
is there anything wrong with my implementation ?

**Comment by penleychan** [comment]
You need to provide the available locales on your Parser.
See the default parser:
https://github.com/penleychan/ngx-transloco-router/blob/master/libs/ngx-transloco-router/src/lib/localize-router.parser.ts#L540

Also since you're doing SSR make sure you have `fallbackLang` configure on your `TRANSLOCO_CONFIG`

**Comment by penleychan** [comment]
Closing ticket, as no activity going on here.
